// City Database with IANA Timezone Data
// All city names in Traditional Chinese (繁體中文)

export const CITY_DATABASE = [
  {
    id: '1',
    name: '台北',
    sub: 'Taipei',
    zone: 'Asia/Taipei',
    flag: '🇹🇼',
    keywords: ['taipei', '台北', 'taiwan', '台灣'],
  },
  {
    id: '2',
    name: '東京',
    sub: 'Tokyo',
    zone: 'Asia/Tokyo',
    flag: '🇯🇵',
    keywords: ['tokyo', '東京', 'japan', '日本'],
  },
  {
    id: '3',
    name: '紐約',
    sub: 'New York',
    zone: 'America/New_York',
    flag: '🇺🇸',
    keywords: ['new york', 'ny', '紐約', 'usa'],
  },
  {
    id: '4',
    name: '倫敦',
    sub: 'London',
    zone: 'Europe/London',
    flag: '🇬🇧',
    keywords: ['london', '倫敦', 'uk', 'england'],
  },
  {
    id: '5',
    name: '巴黎',
    sub: 'Paris',
    zone: 'Europe/Paris',
    flag: '🇫🇷',
    keywords: ['paris', '巴黎', 'france'],
  },
  {
    id: '6',
    name: '柏林',
    sub: 'Berlin',
    zone: 'Europe/Berlin',
    flag: '🇩🇪',
    keywords: ['berlin', '柏林', 'germany', '德國'],
  },
  {
    id: '7',
    name: '雪梨',
    sub: 'Sydney',
    zone: 'Australia/Sydney',
    flag: '🇦🇺',
    keywords: ['sydney', '雪梨', 'australia', '澳洲'],
  },
  {
    id: '8',
    name: '新加坡',
    sub: 'Singapore',
    zone: 'Asia/Singapore',
    flag: '🇸🇬',
    keywords: ['singapore', '新加坡'],
  },
  {
    id: '9',
    name: '香港',
    sub: 'Hong Kong',
    zone: 'Asia/Hong_Kong',
    flag: '🇭🇰',
    keywords: ['hong kong', '香港', 'hk'],
  },
  {
    id: '10',
    name: '首爾',
    sub: 'Seoul',
    zone: 'Asia/Seoul',
    flag: '🇰🇷',
    keywords: ['seoul', '首爾', 'korea', '韓國'],
  },
  {
    id: '11',
    name: '洛杉磯',
    sub: 'Los Angeles',
    zone: 'America/Los_Angeles',
    flag: '🇺🇸',
    keywords: ['los angeles', 'la', '洛杉磯', 'usa'],
  },
  {
    id: '12',
    name: '舊金山',
    sub: 'San Francisco',
    zone: 'America/Los_Angeles',
    flag: '🇺🇸',
    keywords: ['san francisco', 'sf', '舊金山', 'usa'],
  },
  {
    id: '13',
    name: '上海',
    sub: 'Shanghai',
    zone: 'Asia/Shanghai',
    flag: '🇨🇳',
    keywords: ['shanghai', '上海', 'china', '中國'],
  },
  {
    id: '14',
    name: '杜拜',
    sub: 'Dubai',
    zone: 'Asia/Dubai',
    flag: '🇦🇪',
    keywords: ['dubai', '杜拜', 'uae'],
  },
  {
    id: '15',
    name: '莫斯科',
    sub: 'Moscow',
    zone: 'Europe/Moscow',
    flag: '🇷🇺',
    keywords: ['moscow', '莫斯科', 'russia'],
  },
];

export default CITY_DATABASE;
